objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Accountscon.cls
public class Accountscon {
    public Account acc;
    public Account acc2;
    public Accountscon(){
        acc = new Account(Name = 'swasa', ShippingStreet = 'ashford', ShippingCity = 'Herndon', ShippingState = 'VA', ShippingCountry = 'USA');
        system.debug('acc===>'+acc);
        insert acc;
        mymethod();
            }
    public void mymethod(){
        acc2 = new account ();
        acc2.Name= 'swift';
        acc2.Rating= 'Hot';
        acc2.Active__c = 'Yes';
        acc2.Account_Type__c = 'Personal';
         system.debug('acc2===>'+acc2);
         insert acc2;
        system.debug('acc2===>'+acc2);
        
    }
    

}