objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_workflow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account workflow</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>consample__c</fullName>
        <label>consample</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConAccounts.cls
public class ConAccounts {
    public string Name ='shivani';
    public string Type = 'Customer - Channel';
    public Contact ct;
    public Account acc;
  
    public ConAccounts(string st){
        system.debug('ct::::>'+ ct);
        ct = new Contact();
       ct.Salutation = 'Mrs.';
       ct.Firstname = 'eva';
       ct.Lastname = 'Reddy';
       ct.Level__c = 'Secondary';
	   ct.Phone = '6589784521';
	   ct.LeadSource = 'Phone Inquiry';
	   ct.consample__c = 'daksh and dhatri';
        system.debug('ct::::>'+ ct);
        insert ct; 
         myacc1();
      
    }
    public void myacc1(){
        system.debug('acc::::>'+ acc); 
        acc = new Account();
        acc.Name = Name;
        acc.ParentId = '0013h00000HBviU';
        acc.Site = 'www.google.com';
        acc.Type = Type;
        acc.AnnualRevenue= 260000;
        acc.Account_workflow__c = '0013h00000HBviU';
        acc.BillingCity = 'HYD';
        acc.BillingCountry = 'IND';
        acc.AccountSource = 'Public Relations';
        acc.Active__c = 'Yes';
        acc.Account_Type__c = 'Personal';
        acc.AccountSource ='Public Relations';
        acc.Industry ='Government';
         insert acc;
        system.debug('acc::::>'+ acc); 
       
      
    }
 
}