objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>consample__c</fullName>
        <label>consample</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Contact_Apex.cls
public class Contact_Apex {
public Contact ct;
    public Account acc2;
    public Contact_Apex(){
        ct = new Contact();
      system.debug('ct....>'+ct);
       ct.Salutation = 'Mrs.';
       ct.Firstname = 'kruti';
       ct.Lastname = 'desai';
       ct.Level__c = 'Secondary';
	   ct.Phone = '6589784521';
	   ct.LeadSource = 'Phone Inquiry';
	   ct.consample__c = 'daksh and dhatri';
        system.debug('ct::::>'+ ct);
        insert ct; 
        mymethacc();
    }
    public void mymethacc(){ 
        acc2 = new account ();
        acc2.Name= 'swiftone';
        acc2.Rating= 'Cold';
        acc2.Active__c = 'No';
        acc2.Account_Type__c = 'Joint';
        acc2.Phone = '6547892130';
        acc2.AccountSource = 'Phone Inquiry';
        system.debug('acc2===>'+acc2);
        insert acc2;
        system.debug('acc2===>'+acc2);
        
    }
  
}