objects/Account.object
<CustomObject>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpsellOpportunity__c</fullName>
        <label>Upsell Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Apex5.cls
public class Apex5 {
    public integer batchsize = 60;
    public account acc =new account();
    public Apex5(){
         system.debug('acc===>'+ acc);
        acc.Name = 'Vani';
        acc.AccountNumber = '345';
        acc.Site = 'hyd';
        acc.Type= 'Customer - Direct';
        acc.Rating = 'Hot';
        acc.Phone = '32165649870';
        acc.Industry = 'Apparel';
        acc.SLA__c ='Gold';
        acc.UpsellOpportunity__c= 'Maybe';
        system.debug('acc===>'+ acc);
        insert acc;
    }
         

}