objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Batches</relationshipLabel>
        <relationshipName>Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business__c.object
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Bank_details__c</fullName>
        <inlineHelpText>provide bank details</inlineHelpText>
        <label>Bank details</label>
        <length>14</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Batch__c.business__c</field>
                <operation>equals</operation>
                <valueField>$Source.Business__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>students</relationshipLabel>
        <relationshipName>students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>students list</relationshipLabel>
        <relationshipName>students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>email_address__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>email address</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/stu_ternary.cls
public class stu_ternary {
    public stu_ternary(){
        stumeth();
       
    }
    public void  stumeth(){
        for (integer i=0; i<=3; i++){
             system.debug('i.....' + i);
            student__C stu =new student__c();
            stu.name = (i==0) ? 'f1' :((i==1) ? 'f2' : ((i==2) ? 'f3': ((i==3) ? 'f4' : '')));
                stu.Bank_details__c = (i==0  ? 'kourw12345678': (i==1 ? 'sdads8956135' : (i==2 ? 'ssf457896' : (i==3 ? 'dfgsf7980': ''))));
                //stu.Batch__c = (i==0  ? 'a043h00000LwRA5': (i==1 ? 'a043h00000LwRA5' : (i==2 ? 'a043h00000LwRAK' : (i==3 ? 'a043h00000LwRAK': ''))));
            stu.Business__c = (i==0  ? 'a033h000004visS': (i==1 ? 'a033h000004visS' : (i==2 ? 'a033h000004visS' : (i==3 ? 'a033h000004visS': ''))));
            stu.email_address__c =(i==0  ? 'kour1@gmail.com': (i==1 ? 'sdads1@gmail.com' : (i==2 ? 'ssf1@gmail.com' : (i==3 ? '1dfgdfg@gmail.com': ''))));
            insert stu;
        }
       
    }
        
    }