objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_time__c</fullName>
        <label>Batch time</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Batch__c.business__c</field>
                <operation>equals</operation>
                <valueField>$Source.Business__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>students</relationshipLabel>
        <relationshipName>students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Soql_parent2.cls
public class Soql_parent2 {
        public Soql_parent2(){
        soqloptydata();
    }
    public void soqloptydata(){
        list <student__c> stlist = [select id, name, Batch__r.Name, Batch__r.Ownerid, Batch__r.Batch_time__c, Batch__r.Start_date__c from student__C];
        for(student__c s :stlist){
        system.debug('id--->' + s.id+ '===st.name===>'+ s.name +'<===batchname===>'+ s.Batch__r.Name + '===Ownerid=====>'+ s.Batch__r.Ownerid + '===Batch time===>'+ s.Batch__r.Batch_time__c  + '===Start date====>' + s.Batch__r.Start_date__c);
            } 
        
    }

}