objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_time__c</fullName>
        <label>Batch time</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Name__c</fullName>
        <label>Staff Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ravi</fullName>
                </value>
                <value>
                    <fullName>john</fullName>
                </value>
                <value>
                    <fullName>Mohan</fullName>
                </value>
                <value>
                    <fullName>gopi</fullName>
                </value>
                <value>
                    <fullName>guna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Batches</relationshipLabel>
        <relationshipName>Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>Modules__c</fullName>
        <label>Modules</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Lightning</fullName>
                </value>
                <value>
                    <fullName>SAAS Admin</fullName>
                </value>
                <value>
                    <fullName>SAAS DEV</fullName>
                </value>
                <value>
                    <fullName>AWS Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_list__c</fullName>
        <label>Staff list</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mohan</fullName>
                </value>
                <value>
                    <fullName>John</fullName>
                </value>
                <value>
                    <fullName>Balu</fullName>
                </value>
                <value>
                    <fullName>Ravi</fullName>
                </value>
                <value>
                    <fullName>Ram</fullName>
                </value>
                <value>
                    <fullName>Gopi</fullName>
                </value>
                <value>
                    <fullName>Guna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Bank_details__c</fullName>
        <inlineHelpText>provide bank details</inlineHelpText>
        <label>Bank details</label>
        <length>14</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Batch__c.business__c</field>
                <operation>equals</operation>
                <valueField>$Source.Business__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>students</relationshipLabel>
        <relationshipName>students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>students list</relationshipLabel>
        <relationshipName>students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>NZ</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>IND</fullName>
                    <default>true</default>
                    <label>IND</label>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                    <isActive>false</isActive>
                    <label>INDIA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Is_fee_paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is fee paid?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>courses__c</fullName>
        <label>courses</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAAS</fullName>
                </value>
                <value>
                    <fullName>AWS</fullName>
                </value>
                <value>
                    <fullName>SFDC</fullName>
                </value>
                <value>
                    <fullName>vb</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email_address__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>email address</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>howmuch__c</fullName>
        <label>how much</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Inner_stu.cls
public class Inner_stu {
public Busi bs;
public Batches boc;
public student__c stu;
public Inner_stu(){
    boc = new Batches();
        system.debug('stu---->'+stu);
        stu = new student__c();
        stu.Name = 'krish';
        stu.Bank_details__c = 'hn5689741231'; 
        stu.email_address__c = 'krishdummy@gmail.com';
        stu.Is_fee_paid__c = true;
        stu.Discount__c = 20;
        stu.howmuch__c = 20000;
        stu.Batch__c = 'a043h00000LwRA5';
        stu.courses__c = 'SFDC';
        stu.Business__c = 'a033h000004visS';
        stu.Country__c ='IND';
        stu.CurrencyIsoCode = 'INR';
        stu.RecordTypeId = '0123h000000QqO9';
        system.debug('stu---->'+stu);
        
    } 
    public class Busi{
        Business__c bs = new Business__c();
        public Busi(){ 
            mybusi('SFDC');
        }
        public void mybusi(string st){
         Business__c b =new Business__c();
          b.Name= 'Trial';
        b.Staff_list__c = 'Mohan; Ravi;Guna';
        b.Modules__c = 'Admin; Development; Integration; UAT; Lightning';
        system.debug('b---->'+  b);
       string coachmodule =st; 
           
    }
    }
    public class Batches{    
    Batch__c btc = new Batch__c();
        public Batches(){
        mybc('7am');
       Busi bs = new Busi();
        }
        public  string mybc(string se ){
        Batch__c bc = new Batch__c();
        bc.Name = 'Sample';
        bc.Batch_time__c ='7am batch';
        bc.business__c = 'a033h000004visS';
        bc.Batch_time__c = '7am';
        bc.Staff_Name__c  = 'Ravi';
            system.debug('bc===>'+bc);
        return se;
            
        }
    }
}