objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>India_Students_Count__c</fullName>
        <label>India Students Count</label>
        <summaryFilterItems>
            <field>student__c.Country__c</field>
            <operation>equals</operation>
            <value>IND</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>student__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>USA student Record Type</value>
        </summaryFilterItems>
        <summaryForeignKey>student__c.Business__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>students list</relationshipLabel>
        <relationshipName>students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/soql_parent1.cls
public class soql_parent1 {
        public Soql_parent1(){
        soqloptydata();
    }
    public void soqloptydata(){
        list <student__c> stlist = [select id, name, Business__r.Owner.Username, Business__r.Owner.Email, Business__r.Owner.Profile.Name, Business__r.Owner.Profile.Id, Business__r.India_Students_Count__c, Business__r.Name from student__c];
        for(student__c st : stlist){
            system.debug('id--->' +st.id+ '===st.name===>'+ st.name + '===Ownerid=====>'+ st.Business__r.Ownerid + '===India_Students_Count__c====>' + st.Business__r.India_Students_Count__c + '===Name===>' + st.Business__r.Name +'===profile Id===>'+ st.Business__r.Owner.Profile.Id +'===profile name===>'+st.Business__r.Owner.Profile.Name);
        
        
    }

}
}