objects/Business__c.object
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Bank_details__c</fullName>
        <inlineHelpText>provide bank details</inlineHelpText>
        <label>Bank details</label>
        <length>14</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>students list</relationshipLabel>
        <relationshipName>students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>email_address__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>email address</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/If_stu.cls
public class If_stu {
    public string stuname;
    public integer stucount;
    public student__c stu;
    public if_stu(string Name){
        stumeth(Name);
    }
    public void stumeth(string Name){
        stu = new student__c();
        if (stu.Name == 'swetha'){
            stu.email_address__c = 'sweswa@gmail.com';
            stu.Bank_details__c = '456978653sdas';
            stu.Business__c = 'a033h000004visX';
            stucount = 10;
        }else if (stu.Name == 'sharath'){
            stucount = 20;
       // } else if (stu.Name == 'shiva'){
       //     stu.email_address__c = 'shiva0987@gmail.com'
           // stu.Bank_details__c = '4578f';
           // stu.Business__c = 'a033h000004visX';
            //stucount= 30;
        }else {
            stucount = 0;
        
        }
        insert stu;
        system.debug('stucount '  +stucount);
    }
    
}