objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Phone_number__c</fullName>
        <label>Phone number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>consample__c</fullName>
        <label>consample</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Main_Inner.cls
public class Main_Inner {
public string campaignname = 'Dasara sale';
public Campaign camp;
public cls2 cs;
public cls3 cl = new cls3();
public Main_Inner(){ 
    camp = new Campaign();
    mycamp();
}
    public void mycamp(){
     Campaign ca = new Campaign();
     ca.Name = 's1';
     ca.CurrencyIsoCode = 'INR';
     ca.Phone_number__c = '3698547210';
     system.debug('camp====>......'+ca);
        cs = new cls2();
         }  
   public class cls2 {
        public string leadname = 'G1';
        Lead ld = new Lead();
    public cls2(){
        Lead l = new Lead();
        l.LastName = 'emma';
        l.Company = 'TATA';
        l.CurrencyIsoCode = 'INR';
        l.Status = 'Closed - Converted';  
        system.debug('l====>......'+l);
        
        }  
   }
        public class Cls3{
        public string contactname= 'swathi';
        Contact ct =new Contact();
        public cls3(){
       Contact co = new Contact();
       co.Salutation = 'Mrs.';
       co.Firstname = 'kutti';
       co.Lastname = 'de';
       co.Level__c = 'Secondary';
	   co.Phone = '6589784521';
	   co.LeadSource = 'Phone Inquiry';
	   co.consample__c = 'daksh';
        system.debug('co::::>'+ co);
        } 
}

}